FinalProject/Models/Quote.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProject.Models
{
    public class Quote
    {
        public int QuoteID { get; set; }
        public DateTime Date { get; set; }
        public string Content { get; set; }
        public string Quotee { get; set; }
        public string Category { get; set; }
        public List<Comment> Comments { get; set; }         
    }


}

FinalProject/Controllers/QuoteController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FinalProject.Models;

namespace FinalProject.Controllers
{
    public class QuoteController : Controller
    {

        private readonly IQuoteRepo repo;
        private readonly QuoteGenerator QuoteAPI;

        public QuoteController(IQuoteRepo quoteRepo)
        {
            repo = quoteRepo;
            QuoteAPI = new QuoteGenerator();
        }

        /// <summary>
        /// If Todays quote does not exist, generate a new one from API. Then Redirect to view this weeks quotes.
        /// </summary>
        public IActionResult Index()
        {            
            CheckTodaysQuoteExists();
            return View(repo.GetThisWeeksQuotes());
        }

        /// <summary>
        /// If todays quote does not exist, generate new one from API. Then Redirect to view todays quote using most recent quote.
        /// </summary>
        public IActionResult ViewTodaysQuote()
        {
            CheckTodaysQuoteExists();
            return RedirectToAction("ViewQuote", new { id = repo.GetMostRecentQuote().QuoteID });
        }
      
        /// <summary>
        /// Direct to view the page for the specified QuoteID
        /// </summary>
        public IActionResult ViewQuote(int id)
        {
            // obtain the quote with matching quoteID from Database
            var quote = repo.GetQuote(id);

            // assign comments to that quote
            quote.Comments = repo.GetCommentsById(id).ToList();

            return View(quote);
        }

        /// <summary>
        /// If the QuoteID provided exists then view page to insert comment for that page, otherwise view QuoteNotFound page.
        /// </summary>
        public IActionResult InsertComment(int id)
        {
            // create a new instance of Comment and assign the QuoteID and ParentQuote based on the quoteID provided
            var comment = new Comment() {
                QuoteID = id,
                ParentQuote = repo.GetQuote(id)        
            };
            
            // if the QuoteID provided is found in the Database then go to View InsertComment page
            return repo.GetQuote(id) == null ? View("QuoteNotFound") : View("InsertComment", comment);
        }

        /// <summary>
        /// Insert the provided comment to Database then redirect to ViewQuote page for the QuoteID of the comment.
        /// </summary>
        public IActionResult InsertCommentToDatabase(Comment commentToInsert)
        {
            // Insert the provided comment into the database.
            repo.InsertComment(commentToInsert);

            // redirect to view the page for the quote we just commented on.
            return RedirectToAction("ViewQuote", new { id = commentToInsert.QuoteID });
        }

        /// <summary>
        /// If todays quote exists then remove it from the database. Then return to HomeController.Index()
        /// </summary>
        public IActionResult DeleteTodaysQuote()
        {
            // Delete todays quote if it exists in the Database
            if (repo.TodaysQuoteExists()) repo.DeleteQuote(repo.GetMostRecentQuote()); 
            
            // Return to home page after deleting a quote
            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// If today's quote does not exist then generate a new quote.
        /// </summary>
        void CheckTodaysQuoteExists()
        {
            // if todays quote does not exist
            if (!repo.TodaysQuoteExists())
            {
                // Insert New Quote Pulled from API
                repo.InsertQuote(QuoteAPI.Generate());
            }
        }

    }
}

FinalProject/Views/Quote/Index.cshtml
@model IEnumerable<Quote>

<link rel="stylesheet" href="~/css/quote.css">

<main>

    <section id="today-quote">

        <h2>Today's Quote</h2>
        <div id="quote"> <h3>@Model.First().Content</h3> </div>
        <div id="quotee"> <p>@Model.First().Quotee</p> </div>
        <a id="link-centered-bordered" href=/Quote/InsertComment/@Model.First().QuoteID>
            Submit Your Opinion About This Quote </a>

        <section id="comments">
        <div id="comments-container">
        <h2>Comments About Today's Quote</h2>
            @if (Model.First().Comments.Count > 0)
            {
                @foreach (var comment in @Model.First().Comments)
                {
                    <figure id="comment">
                        <figcaption>@comment.Author - @comment.CommentDate</figcaption>
                        <p id="comment-content">@comment.Content</p>
                    </figure>
                }
            }
            else 
            {
                <p id="no-comments">No one has commented yet....<br/> Submit your opinion to be the first to comment!</p>
            } 
            </div>
    </section>

    </section>

    <section id="prev-quotes">
        <h2>This Weeks Quotes</h2>

        <table class="table">

            <tr>
                <th>Date</th>
                <th id="quote-header">Quote</th>
                <th>Quotee</th>
                <th>Submit Input</th>

            </tr>

            @foreach (var quote in Model.ToArray().Skip(1))
            {
                <tr>
                    <td id="day-of-week"><a href=/Quote/ViewQuote/@quote.QuoteID>@quote.Date.ToString("MM/dd/yyyy")</a></td>
                    <td id="quote-of-week">@quote.Content</td>
                    <td id="quotee-of-week">@quote.Quotee.Remove(0,1)</td>
                    <td id="comment-quote-of-week"><a href=/Quote/InsertComment/@quote.QuoteID>Submit Comment</a></td>
                </tr>
            }

        </table>
    </section>

</main>

FinalProject/Views/Quote/InsertComment.cshtml
@model Comment

@{
    ViewData["Title"] = "Share Your Comment";
}

<link rel="stylesheet" href="~/css/quote.css">
<link rel="stylesheet" href="~/css/InsertQuote.css">

<div id="quote">
    <h3>@Model.ParentQuote.Content</h3>
</div>

<div id="quotee">
    <p>@Model.ParentQuote.Quotee</p>
</div>

<section id="comments">
    <!-- Form Goes Here -->
    <div id="comment-form">
        <h2>Submit Your Comments</h2>

        <!-- TODO: I'm sending null data to InsertCommentToDatabase here-->
        @using (Html.BeginForm("InsertCommentToDatabase", "Quote", "Post"))
        {
            <input asp-for="QuoteID" type="hidden" value="@Model.ParentQuote.QuoteID" />

            <label asp-for="Author">Your Name: </label>
            <input name="Author" id="name-input" type="text" class="form-control" placeholder="Enter your name here" required /> <br />

            <label asp-for="Content">Your feelings about this quote:</label> <br />
            <textarea id="comment-input" name="Content" class="form-control" required></textarea>
            <div id="form-submit-container">
            <input type="submit" id="form-submit" value="Submit Your Comments" />
            </div>
        }
    </div>


    @if (Model.ParentQuote.Comments != null)
    {
        <div id="comments-container">
            <h2>Comments About This Quote</h2>
            @foreach (var comment in @Model.ParentQuote.Comments)
            {
                <figure>
                    <figcaption>@comment.Author - @comment.CommentDate</figcaption>
                    <p id="comment">@comment.Content</p>
                </figure>
            }
        </div>
    }

</section>

FinalProject/Views/Quote/ViewQuote.cshtml
@model Quote

<link rel="stylesheet" href="~/css/quote.css">

<main>

    <section id="today-quote">
        <div id="quote">
            <h3>@Model.Content</h3>
        </div>

        <div id="quotee">
            <p>@Model.Quotee</p>
        </div>

        <a id="link-centered-bordered" href=/Quote/InsertComment/@Model.QuoteID>
            Submit Your Opinion About This Quote
        </a>

            <section id="comments">
                <div id="comments-container">
                    <h2>Comments About This Quote</h2>
                    @if (Model.Comments.Count > 0)
                    {
                        @foreach (var comment in @Model.Comments)
                        {
                            <figure id="comment">
                                <figcaption>@comment.Author - @comment.CommentDate</figcaption>
                                <p id="comment-content">@comment.Content</p>
                            </figure>
                        }
                    }
                    else
                    {
                        <p id="no-comments">No one has commented yet....<br /> Submit your opinion to be the first to comment!</p>
                    }
                </div>
            </section>


        </section>

    </section>

</main>